apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: performance-truedat

resources:
  - git@gitlab.bluetab.net:dgs-core/true-dat/td-k8s-base.git/services/external/metabase?ref=5.7.0
  - git@gitlab.bluetab.net:dgs-core/true-dat/td-k8s-base.git/jobs/metabase-migrations?ref=5.7.0
  - git@gitlab.bluetab.net:dgs-core/true-dat/td-k8s-base.git/jobs/createdb?ref=5.7.0
  - git@gitlab.bluetab.net:dgs-core/true-dat/td-k8s-base.git/secrets/metabase?ref=5.7.0
  - ingress.yml

secretGenerator:
  - name: metabase
    behavior: merge
    type: Opaque
    envs:
      - secret.env

configMapGenerator:
  - name: metabase
    behavior: merge
    literals:
      - MB_SITE_URL=https://metabase.performance.truedat.io

patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/envFrom/0/configMapRef/name
        value: metabase
      - op: replace
        path: /spec/template/spec/containers/0/envFrom/1/secretRef/name
        value: metabase
      - op: replace
        path: /metadata/name
        value: createdb-metabase
    target:
      kind: Job
      name: createdb
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: metabase.performance.truedat.io
    target:
      kind: Ingress
      name: metabase
  
commonAnnotations:
  info/description: Reporting

