apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: performance-truedat

resources:
  - git@gitlab.bluetab.net:dgs-core/true-dat/td-k8s-base.git/config/redis?ref=5.7.0
  - git@gitlab.bluetab.net:dgs-core/true-dat/td-k8s-base.git/persistence/redis-external?ref=5.7.0

patches:
  - patch: |-
      - op: replace
        path: /spec/externalName
        value: perf-td-ref-cache-subnet.olp6pf.0001.euw1.cache.amazonaws.com
    target:
      kind: Service
      name: redis
