apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: performance-truedat

resources:
  - git@gitlab.bluetab.net:dgs-core/true-dat/td-k8s-base.git/config/elasticsearch?ref=5.7.0

configMapGenerator:
  - name: elastic
    behavior: create
    literals:
      - ES_URL=https://vpc-perf-td-ref-search-pxi6mpugh5nerdzxyqvlr5uku4.eu-west-1.es.amazonaws.com
      - ES_HOST=https://vpc-perf-td-ref-search-pxi6mpugh5nerdzxyqvlr5uku4.eu-west-1.es.amazonaws.com
      - ES_PORT=443
